development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: q_project_development
  pool: 5
  username: kvarma
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: q_project_test_<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: kvarma
  host: localhost
  port: 5432

