production:
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: q_project_development
  pool: 5
  username: kvarma
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: q_project_test_<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: kvarma
  host: localhost
  port: 5432

